//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/arindraaribudi/cert-manager-ext-issuer-secret-manager/api/v1alpha1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSCertificateClusterIssuer) DeepCopyInto(out *AWSCertificateClusterIssuer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSCertificateClusterIssuer.
func (in *AWSCertificateClusterIssuer) DeepCopy() *AWSCertificateClusterIssuer {
	if in == nil {
		return nil
	}
	out := new(AWSCertificateClusterIssuer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AWSCertificateClusterIssuer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSCertificateClusterIssuerList) DeepCopyInto(out *AWSCertificateClusterIssuerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AWSCertificateClusterIssuer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSCertificateClusterIssuerList.
func (in *AWSCertificateClusterIssuerList) DeepCopy() *AWSCertificateClusterIssuerList {
	if in == nil {
		return nil
	}
	out := new(AWSCertificateClusterIssuerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AWSCertificateClusterIssuerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSCertificateIssuer) DeepCopyInto(out *AWSCertificateIssuer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSCertificateIssuer.
func (in *AWSCertificateIssuer) DeepCopy() *AWSCertificateIssuer {
	if in == nil {
		return nil
	}
	out := new(AWSCertificateIssuer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AWSCertificateIssuer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSCertificateIssuerList) DeepCopyInto(out *AWSCertificateIssuerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AWSCertificateIssuer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSCertificateIssuerList.
func (in *AWSCertificateIssuerList) DeepCopy() *AWSCertificateIssuerList {
	if in == nil {
		return nil
	}
	out := new(AWSCertificateIssuerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AWSCertificateIssuerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSCertificateIssuerSpec) DeepCopyInto(out *AWSCertificateIssuerSpec) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(AWSSecretRef)
		**out = **in
	}
	if in.NamespaceFilter != nil {
		in, out := &in.NamespaceFilter, &out.NamespaceFilter
		*out = new(apiv1alpha1.NamespaceFilter)
		(*in).DeepCopyInto(*out)
	}
	out.ResyncInterval = in.ResyncInterval
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSCertificateIssuerSpec.
func (in *AWSCertificateIssuerSpec) DeepCopy() *AWSCertificateIssuerSpec {
	if in == nil {
		return nil
	}
	out := new(AWSCertificateIssuerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSCertificateIssuerStatus) DeepCopyInto(out *AWSCertificateIssuerStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSCertificateIssuerStatus.
func (in *AWSCertificateIssuerStatus) DeepCopy() *AWSCertificateIssuerStatus {
	if in == nil {
		return nil
	}
	out := new(AWSCertificateIssuerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSSecretRef) DeepCopyInto(out *AWSSecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSSecretRef.
func (in *AWSSecretRef) DeepCopy() *AWSSecretRef {
	if in == nil {
		return nil
	}
	out := new(AWSSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TencentCertificateClusterIssuer) DeepCopyInto(out *TencentCertificateClusterIssuer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TencentCertificateClusterIssuer.
func (in *TencentCertificateClusterIssuer) DeepCopy() *TencentCertificateClusterIssuer {
	if in == nil {
		return nil
	}
	out := new(TencentCertificateClusterIssuer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TencentCertificateClusterIssuer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TencentCertificateClusterIssuerList) DeepCopyInto(out *TencentCertificateClusterIssuerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TencentCertificateClusterIssuer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TencentCertificateClusterIssuerList.
func (in *TencentCertificateClusterIssuerList) DeepCopy() *TencentCertificateClusterIssuerList {
	if in == nil {
		return nil
	}
	out := new(TencentCertificateClusterIssuerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TencentCertificateClusterIssuerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TencentCertificateIssuer) DeepCopyInto(out *TencentCertificateIssuer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TencentCertificateIssuer.
func (in *TencentCertificateIssuer) DeepCopy() *TencentCertificateIssuer {
	if in == nil {
		return nil
	}
	out := new(TencentCertificateIssuer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TencentCertificateIssuer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TencentCertificateIssuerList) DeepCopyInto(out *TencentCertificateIssuerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TencentCertificateIssuer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TencentCertificateIssuerList.
func (in *TencentCertificateIssuerList) DeepCopy() *TencentCertificateIssuerList {
	if in == nil {
		return nil
	}
	out := new(TencentCertificateIssuerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TencentCertificateIssuerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TencentCertificateIssuerSpec) DeepCopyInto(out *TencentCertificateIssuerSpec) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(TencentSecretRef)
		**out = **in
	}
	if in.NamespaceFilter != nil {
		in, out := &in.NamespaceFilter, &out.NamespaceFilter
		*out = new(apiv1alpha1.NamespaceFilter)
		(*in).DeepCopyInto(*out)
	}
	out.ResyncInterval = in.ResyncInterval
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TencentCertificateIssuerSpec.
func (in *TencentCertificateIssuerSpec) DeepCopy() *TencentCertificateIssuerSpec {
	if in == nil {
		return nil
	}
	out := new(TencentCertificateIssuerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TencentCertificateIssuerStatus) DeepCopyInto(out *TencentCertificateIssuerStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TencentCertificateIssuerStatus.
func (in *TencentCertificateIssuerStatus) DeepCopy() *TencentCertificateIssuerStatus {
	if in == nil {
		return nil
	}
	out := new(TencentCertificateIssuerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TencentSecretRef) DeepCopyInto(out *TencentSecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TencentSecretRef.
func (in *TencentSecretRef) DeepCopy() *TencentSecretRef {
	if in == nil {
		return nil
	}
	out := new(TencentSecretRef)
	in.DeepCopyInto(out)
	return out
}
